;(function(window){var _guid=0;function each(arg,callback){if(Object.prototype.toString.call(arg)=="[object Array]"){for(var i=0;i<arg.length;i++){callback(arg[i],i);}}
else if(Object.prototype.toString.call(arg)=="[object Object]"){for(var p in arg){arg.hasOwnProperty(p)&&callback(arg[p],p);}}}
function addEvt(el,type,hdl){var callback=function(evt){var evt=window.event||evt,target=evt.srcElement||evt.target;hdl(evt,target);};window.addEventListener&&el.addEventListener(type,callback,false)||window.attachEvent&&el.attachEvent('on'+type,callback);}
function bindEvt(el,type,conf){addEvt(el,type,function(evt,target){var _event=target.getAttribute('_event');conf[_event]&&conf[_event].call(target);})}
function getParentAttr(el,attr){var val;while(el){if(val=e.getAttribute(attr)){return val;}
el=el.parentNode;}
return null;}
function getCookie(name){var r=new RegExp("(?:^|;+|\\s+)"+name+"=([^;]*)"),m=document.cookie.match(r);return(!m?"":m[1]);}
function getLoginUin(){var uin=getCookie('uin')||getCookie('zzpaneluin');if(uin.length>4){return new Number(uin.replace(/o(\d+)/g,'$1'));}
return 0;}
function getDialogHtml(data){data.height=data.height||456;var template=['<div>','<a style="font:500 18px/38px Tahoma;color:#A7A7A7;position:absolute;top:4px;left:445px;text-decoration:none;cursor:pointer" _event="close">x</a>','<iframe  allowTransparency="true" src="<%url%>" width="<%width%>px" height="<%height%>px" frameborder="0" src="" scrolling="no" ></iframe>','</div>'].join('');each(data,function(item,p){template=template.replace(new RegExp('<%'+p+'%>','g'),item);});return template;}
function getToken(){var hash=5381,str=getCookie('skey');for(var i=0,len=str.length;i<len;++i){hash+=(hash<<5)+str.charCodeAt(i);}
return hash&0x7fffffff;}
function Dao(cgi,param,fn){var _param={callback:'QQReminder._',uin:getLoginUin(),src:0,from:1,g_tk:getToken(),_:+new Date()};var arr=[];each(param,function(item,p){item&&(_param[p]=item);})
each(_param,function(item,p){arr.push(p+'='+encodeURIComponent(item));});new Loader().request('http://calendar.snsapp.qq.com/cgi-bin/'+cgi+'?'+arr.join('&'),fn);}
function Loader(){this.node=document.createElement('script');this.node.type='text/javascript';this.node.async=true;this.fn=null;this.script=document.getElementsByTagName('script')[0];this.request=function(src,fn){this.node.src=src;this.fn=fn;this.onload();this.script.parentNode.insertBefore(this.node,this.script);};this.onload=function(){var node=this.node,that=this;node.onload=node.onerror=node.onreadystatechange=function(){/loaded|complete|undefined/.test(node.readyState)&&function(){node.onload=node.onerror=node.onreadystatechange=null;node.parentNode.removeChild(node);node=undefined;that.fn(Loader.cache.shift());}();}}}
Loader._=function(data){Loader.cache.push(data);}
Loader.cache=[];function Msg(opt){var hdl=opt;var exec=function(msg){var arr=String(msg).split(':');arr[0]=='qqreminder'&&hdl[arr[1]]&&hdl[arr[1]](arr[2]);};var messageBack=function(e){exec(e.data);};if(window.postMessage){if(window.addEventListener){window.addEventListener("message",messageBack,false);}
else if(window.attachEvent){window.attachEvent("onmessage",messageBack);}}
navigator._postMessage=function(data){exec(data);}
this.abort=function(){if(window.postMessage){if(window.removeEventListener){window.removeEventListener("message",messageBack,false);}else if(window.detachEvent){window.detachEvent("onmessage",messageBack);}}}}
function Dialog(html,opt){function getCurrentStyle(el,attr){if(el.currentStyle){return el.currentStyle[attr];}
else if(window.getComputedStyle){return window.getComputedStyle(el,null)[attr];}
else{return el.style[attr];}}
function compute(attr){return Math.max(document.documentElement[attr],document.body[attr]);}
var _self=this;var p=opt,w=p["width"]||compute("scrollWidth"),h=p["height"]||compute("scrollHeight"),t=p["top"]||0,l=p["left"]||0;var sBg=[["position","absolute"],["background",'#000'],["zIndex","888"],["left","0px"],["top","0px"],["width","100%"],['opacity','0.3'],['filter','Alpha(opacity=30)']];opt.hasNoBg&&sBg.push(["display","none"]);var sWin=[["position","absolute"],["zIndex","999"],["width",w+"px"],["height",h+"px"],["left",(l||Math.floor((compute("clientWidth")-w)/2))+"px"],["top",Math.floor(compute("scrollTop")+t)+"px"],["overflow",'hidden']];if(opt["display"]){sWin.push(["display",opt["display"]]);}
var bg=document.createElement('div');var win=document.createElement("div");win.innerHTML=html||'';win.setAttribute('did','dialog_');each(sWin,function(opt){win.style[opt[0]]=opt[1];});each(sBg,function(opt){bg.style[opt[0]]=opt[1];});document.body.appendChild(bg);document.body.appendChild(win);bg.style.height=Math.max(compute("clientHeight"),compute("scrollHeight"))+"px";this.id=+new Date();this.setContent=function(str){win.innerHTML=str||'';}
this.getContentElem=function(){return win;}
this.getIframeElem=function(){return win.getElementsByTagName("iframe")[0];}
this.resize=function(content){var arr=String(content).split('*'),width=arr[0],height=arr[1];width&&(win.style.width=width+'px',win.style.left=Math.floor((compute("clientWidth")-width)/2)+"px");height&&(win.style.height=height+'px');}
this.success=function(content){_self.onsuccess&&_self.onsuccess(content);_self.onsuccess=null;}
this.error=function(content){_self.onerror&&_self.onerror(content);_self.onerror=null;}
this.unload=function(content){bg.parentNode&&bg.parentNode.removeChild(bg);win.style.display='none';this.onunload&&this.onunload(content);this.onunload=null;_self.msg.abort();}
this.msg=new Msg({success:this.success,close:this.unload,error:this.error,resize:this.resize});bindEvt(win,'click',{'close':function(){_self.unload();}});Dialog.cache[this.id]=this;}
Dialog.cache={};Dialog.closeAll=function(){each(Dialog.cache,function(item){item.unload();})
Dialog.cache={};}
Dialog.getById=function(id){return Dialog.cache[id];}
var Reminder={};Reminder.dialog={addRemind:function(appid,mid,tik,uniqid,opt,showOpt){showOpt=showOpt||{};var dialog=new Dialog('',{width:474,height:336,top:showOpt.top||80,left:showOpt.left,hasNoBg:showOpt.hasNoBg||0});var urlparts=['appid='+appid,'mid='+mid,'uniqid='+uniqid,'tik='+tik];for(var p in opt.params){urlparts.push(p+'='+encodeURIComponent(opt.params[p]));}
urlparts.push('openner='+dialog.id);var url='http://calendar.snsapp.qq.com/cgi-bin/cal_3thpage_inter?'+urlparts.join('&');dialog.setContent(getDialogHtml({url:url,width:580}));dialog.onunload=function(content){opt.onClose&&opt.onClose(content);}
dialog.onsuccess=function(content){opt.onSuccess&&opt.onSuccess({code:0,msg:'添加提醒成功！'});}
dialog.onerror=function(content){opt.onError&&opt.onError(content);}},subscribe:function(appid,itemid,content,opt,showOpt){showOpt=showOpt||{};var dialog=new Dialog('',{width:490,height:265,top:80,top:showOpt.top||80,left:showOpt.left,hasNoBg:showOpt.hasNoBg||0});var urlparts=['appid='+appid,'itemid='+itemid];urlparts.push('openner='+dialog.id);urlparts.push('content='+encodeURIComponent(content));var url='http://calendar.snsapp.qq.com/cgi-bin/cal_subscribe_page?'+urlparts.join('&');dialog.setContent(getDialogHtml({url:url,width:490}));dialog.onunload=function(content){opt.onClose&&opt.onClose(content);}
dialog.onsuccess=function(content){opt.onSuccess&&opt.onSuccess({code:0,msg:'添加订阅成功！'});}},delRemind:function(appid,mid,tik,uniqid,opt,showOpt){opt=opt||{};showOpt=showOpt||{};var dialog=new Dialog('',{width:474,height:188,top:showOpt.top||80,left:showOpt.left,hasNoBg:showOpt.hasNoBg||0});var urlparts=['appid='+appid,'mid='+mid,'uniqid='+uniqid,'tik='+tik,'openner='+dialog.id,'dialogtype=delremind'];if(opt.cycle){urlparts.push('cycle='+opt.cycle);}
var url='http://qzs.qq.com/snsapp/app/bee/widget/inner_dialog.htm?'+urlparts.join("&");dialog.setContent(getDialogHtml({url:url,width:474,height:188}));dialog.onunload=function(){opt.onClose&&opt.onClose();};dialog.onsuccess=function(id){id&&opt.onSuccess&&opt.onSuccess({code:0,msg:'删除提醒成功！'});dialog.unload();};},editeRemind:function(){},closeDialog:function(){Dialog.closeAll();}};Reminder.query={isSet:function(appid,mid,tik,uniqid,onSuccess){new Dao('cal_get_inter',{appid:appid,mid:mid,uniqid:uniqid,tik:tik},function(data){onSuccess(!data.code&&data.isset?1:0);});},isSubscribe:function(appid,itemid,onSuccess){new Dao('cgi_user_subsinfo',{appid:appid,itemid:itemid},function(data){var ret=0;if(!data.code*1&&data.list){for(var i=0,item;item=data.list[i];i++){if(item.appid==appid&&item.items&&item.items.length){for(var j=0,_item;_item=item.items[j];j++){if(_item==itemid){ret=1;break;}}}}}
onSuccess(ret);});},isSubscribe2:function(appid,tmplid,tagid,itemid,onSuccess){new Dao('sub_public_api',{"appid":appid,"tpl_id":tmplid,"tagid":tagid,"itemid":itemid,"cmd":"2","uin":getLoginUin()},function(ret){onSuccess(ret);});}};Reminder.btn={getSubsBtn:function(appid,tmplid,tagid,itemid,opt,showOpt,cb){opt=opt||{};showOpt=showOpt||{};var _uin=getLoginUin();if(_uin){var _self=this;Reminder.query.isSubscribe2(appid,tmplid,tagid,itemid,function(ret){opt.tips=ret.tips;if(ret.code==0&&ret.status==1){cb&&cb(_self._createSubsBtn(appid,tmplid,tagid,itemid,opt,showOpt,"del"));}else{cb&&cb(_self._createSubsBtn(appid,tmplid,tagid,itemid,opt,showOpt,"add"));}});}else{cb&&cb(this._createSubsBtn(appid,tmplid,tagid,itemid,opt,showOpt,"add"));}},_createSubsBtn:function(appid,tmplid,tagid,itemid,opt,showOpt,type){opt=opt||{};opt.params=opt.params||{};opt.needSubs=opt.needSubs||"添加订阅";opt.hasSubs=opt.hasSubs||"取消订阅";opt.style=opt.style||1;var _btnId="qqreminder_btn_"+(_guid++);var _backGroundImg="http://appimg2.qq.com/bee/ac/global/s_btn.png";var aSubsStyle,spanSubsStyle,aHasSubsStyle,spanHasSubsStyle;if(opt.style==1){aSubsStyle='text-decoration:none;background:url(http://appimg2.qq.com/bee/ac/global/s_btn.png) no-repeat;display:inline-block;#display:inline;zoom:1;line-height:40px;padding-left:52px;overflow:visible;';spanSubsStyle='color:#fff;padding-right:20px;height:40px;display:inline-block;#display:inline;zoom:1;background:url(http://appimg2.qq.com/bee/ac/global/s_btn.png) right -50px no-repeat;';aHasSubsStyle='text-decoration:none;background:url(http://appimg2.qq.com/bee/ac/global/s_btn.png) 0 -100px no-repeat;display:inline-block;#display:inline;zoom:1;line-height:40px;padding-left:52px;';spanHasSubsStyle='color:#909090;padding-right:20px;height:40px;display:inline-block;#display:inline;zoom:1;background:url(http://appimg2.qq.com/bee/ac/global/s_btn.png) right -150px no-repeat;';}else if(opt.style==2){aSubsStyle='text-decoration:none;background:url(http://appimg2.qq.com/bee/ac/global/s_btn.png) 0 -200px no-repeat;display:inline-block;#display:inline;zoom:1;line-height:24px; padding-left:36px;';spanSubsStyle='color:#fff;padding-right:16px;height:24px;display:inline-block;#display:inline;zoom:1;background:url(http://appimg2.qq.com/bee/ac/global/s_btn.png) right -234px no-repeat;';aHasSubsStyle='text-decoration:none;background:url(http://appimg2.qq.com/bee/ac/global/s_btn.png) 0 -268px no-repeat;display:inline-block;#display:inline;zoom:1;line-height:24px;padding-left:36px;';spanHasSubsStyle='color:#909090;padding-right:16px;height:24px;display:inline-block;#display:inline;zoom:1;background:url(http://appimg2.qq.com/bee/ac/global/s_btn.png) right -302px no-repeat;';}
var _html=['<a href="javascript:void(0);"  id="'+_btnId+'"  style="">','<span style=""></span>','</a>'].join("");var _div=document.createElement("DIV");_div.innerHTML=_html;var _aElem=_div.getElementsByTagName("A");var _retElem=_aElem[0];var _self=this;var _statusChange=function(hasSubs){var _spanELem=_retElem.getElementsByTagName("SPAN")[0];if(hasSubs){_retElem.setAttribute("_event","del");_retElem.style.cssText=aHasSubsStyle;_spanELem.innerHTML=opt.hasSubs;_spanELem.style.cssText=spanHasSubsStyle;}else{_retElem.setAttribute("_event","add");_retElem.style.cssText=aSubsStyle;_spanELem.innerHTML=opt.needSubs;_spanELem.style.cssText=spanSubsStyle;}};_statusChange(type=="add"?false:true);addEvt(_retElem,"click",function(evt){var _uin=getLoginUin();if(_uin){_self._showProcessDialog(appid,tmplid,tagid,itemid,_retElem.getAttribute("_event"),opt,showOpt,_statusChange);}else{_self._showLoginDialog(showOpt);}});return _retElem;},_showProcessDialog:function(appid,tmplid,tagid,itemid,type,opt,showOpt,statusChangeFn){var _hasNoBg=showOpt.hasNoBg||0;if(type=="add"){_hasNoBg=true;}
var _self=this;var _width=474,_height=245;var dialog=new Dialog('',{width:_width,height:_height,top:showOpt.top||80,left:showOpt.left,hasNoBg:showOpt.hasNoBg||0});var keys=[];for(var key in opt.params){keys.push(key);}
var urlparts=['appid='+appid,'templid='+tmplid,'tagid='+tagid,'itemid='+itemid,'openner='+dialog.id,'dialogtype='+type,'keys='+keys.join(","),'tips='+encodeURIComponent(opt.tips||"")];for(var key in opt.params){urlparts.push(key+'='+encodeURIComponent(opt.params[key]));}
var url='http://qzs.qq.com/snsapp/app/bee/widget/subs_dialog.htm#'+urlparts.join("&");dialog.setContent(getDialogHtml({url:url,width:_width,height:_height}));dialog.onsuccess=function(tips){var _title,_msg;if(type=="add"){_title="订阅"+opt.itemName+"成功";_msg=tips;}else{_title="取消成功";_msg="您将不会收到该订阅的通知消息";}
statusChangeFn&&statusChangeFn(type=="add");dialog.unload();showMsgDialog(_title,_msg,"success");};dialog.onerror=function(msg){dialog.unload();if(msg=="-1001"){_self._showLoginDialog(showOpt);return;}
var _title,_msg;if(type=="add"){_title="订阅失败";_msg=msg;}else{_title="取消失败";_msg=msg;}
showMsgDialog(_title,_msg,"info");};function showMsgDialog(title,msg,type){var _width=474,_height=245;var _msgDialog=new Dialog('',{width:_width,height:_height,top:showOpt.top||80,left:showOpt.left,hasNoBg:showOpt.hasNoBg||0});var urlparts=['openner='+_msgDialog.id,'type='+type,"title="+encodeURIComponent(title),'msg='+encodeURIComponent(msg),'dialogtype=msg'];var url='http://qzs.qq.com/snsapp/app/bee/widget/subs_dialog.htm#'+urlparts.join("&");_msgDialog.setContent(getDialogHtml({url:url,width:_width,height:_height}));}},_showLoginDialog:function(showOpt){var _width=474,_height=265;var _loginDialog=new Dialog('',{width:_width,height:_height,top:showOpt.top||80,left:showOpt.left,hasNoBg:showOpt.hasNoBg||0});var urlparts=['openner='+_loginDialog.id,'dialogtype=login'];var url='http://qzs.qq.com/snsapp/app/bee/widget/subs_dialog.htm#'+urlparts.join("&");_loginDialog.setContent(getDialogHtml({url:url,width:_width,height:_height}));_loginDialog.onsuccess=function(id){_loginDialog.unload();};}};Reminder._=function(data){Loader._(data);}
window.QQReminder={dialog:Reminder.dialog,query:Reminder.query,btn:Reminder.btn,_:Reminder._};})(this)/*  |xGv00|7ec904fa9d4f2a31c14d2f2c6469bb56 */